name: wandel
version: 1.0.0
description: >
    Wandel is a data migration library. Out of the box with mysql-connector based on sqljocky5.
author: Robert Beyer <robert@4stern.net>
dependencies:
    sqljocky5: "^1.0.0"
