include: package:pedantic/analysis_options.yaml

# https://www.dartlang.org/guides/language/analysis-options
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - test/.test_coverage.dart

# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_unused_constructor_parameters
    - avoid_returning_null_for_future
    - avoid_renaming_method_parameters
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_escaping_inner_quotes
    - avoid_double_and_int_checks
    - avoid_bool_literals_in_conditional_expressions
    - camel_case_types
    - directives_ordering
    - empty_constructor_bodies
    - hash_and_equals
    - invariant_booleans
    - list_remove_unrelated_type
    - no_logic_in_create_state
    - no_duplicate_case_values
    - one_member_abstracts
    - only_throw_errors
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_void_to_null
    - slash_for_doc_comments
    - unrelated_type_equality_checks
    # - constant_identifier_names
    # - sort_constructors_first
