name: wandel_postgres
version: 3.1.4
description: >
    wandel_prostgres provide the postgres connector used in wandel package.
homepage: https://github.com/4stern/wandel
environment:
    sdk: ">=2.1.0 <3.0.0"
dependencies:
    wandel: ^3.0.1
    postgres: ^2.1.1
