name: wandel
version: 3.0.0
description: >
    Wandel is a data migration library
homepage: https://github.com/4stern/wandel
environment:
    sdk: ">=2.1.0 <3.0.0"
dev_dependencies:
    sqljocky5: 2.2.1
    wandel_mysql:
        path: ../wandel_mysql
