name: wandel_mysql
version: 3.1.0
description: >
    wandel_mysql provide the mysql connector used in wandel package.
homepage: https://github.com/4stern/wandel
environment:
    sdk: ">=2.1.0 <3.0.0"
dependencies:
    wandel: ^3.0.1
    sqljocky5: ^2.2.1
